### ISSUE TITLE
Write input IDS metadata to jetto.in / jetto.jset

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#109]
From @aaronkho :
The scripts in the `scripts` directory are capable of taking some metadata from the input IDS (shot number, first time slice in core_profiles, machine name) and writing them into the appropriate places within the `jetto.in` and `jetto.jset` files. I think having this functionality in your tool would accelerate the setup of the "base" run, especially in large-scale validation where we ideally want all the JETTO settings to be fixed except for this metadata.

**Comment by stefsmeets** [comment]
Hi @aaronkho , I am looking into this and I was wondering if you can give me some context of what you would like to achieve. We already support some of this workflow I think:

```python
from duqtools.ids import ImasHandle
from duqtools.jetto import read_jset, write_jset

handle_in = ImasHandle(user='g2ssmee', db='jet', shot=1234, run=1111)
handle_out = ImasHandle(user='g2ssmee', db='jet', shot=1234, run=2222)

jset = read_jset('jetto.jset')

jset.set_imas_locations(inp=handle_in, out=handle_out)

write_jset('new_jetto.jset')
```

From the `prepare_im_runs.py`, I see that you also update some other fields. I.e. the user name should be set to multiple fields. Currently we just update the ones that are required for the python config, but that is easily changed.

I can also make the major radius easily accessible so that it can be read/updated in the jset (i.e. `JettoSettings.major_radius`. This is the corresponding IDS path: `equilibrium/vacuum_toroidal_field/r0`, see:
https://github.com/CarbonCollective/fusion-dUQtools/blob/9de484fd6fb26226325d93ac812877de9c2cef00/scripts/prepare_im_runs.py#L535

This would enable something like this:

```python
eq = get_ids_tree(handle_in, 'equilibrium')
jset.major_radius = eq['vacuum_toroidal_field/r0']
```

**Comment by stefsmeets** [comment]
@aaronkho For the impurities, that's essentially 2 things:

1. Some convenient way to set the impurities in the jset
    - I see there are 6 entries in the `jetto.jset`.
    - This could be implemented via some pydantic basemodel representing the impurity dict
2. Some way of extracting these data from the IDS and converting them to a dict
    - These data come from `profiles_1d/0/ion/...`

**Comment by v1kko** [comment]
This links to #220

**Comment by stefsmeets** [comment]
Just wondering where the impurities should be implemented, and whether this is within scope of this tool. Generating self-consistent jetto inputs from IMAS data is not the responsibility of `duqtools`, imo.

@aaronkho @v1kko what do you think?

**Comment by aaronkho** [comment]
The generation of self-consistent JETTO inputs from a given IDS is part of the automation pipeline that we foresee for the large-scale UQ study. However, I think this self-consistency issue can be broken into three categories:
- Plasma scenario / machine configuration (should in principle be via some JINTRAC-IMAS driver)
- Physics module inclusion and physics-related settings consistency (must be done by the user - manually or by loading an old template case)
- Simulation peripherals / metadata (e.g. simulation time, print out times, time step limits, diffusion limits, etc. - currently only in the realm of JAMS, which has no external API for scripting purposes)

In this sense, I envision `duqtools` filling in this third category, effectively providing the "missing API" but only wherever necessary and possible. Since impurities technically belong to the first category, I would agree with @stefsmeets. However, @Marinmepfl requires some automation here and there is no appropriate JINTRAC-IMAS driver yet, thus its inclusion into his `scripts`.

If it is easy to include, I would keep it in scope. However, if it requires large changes in the underlying code structure, then we leave it out for now.

**Comment by stefsmeets** [comment]
Develop a new tool that takes a given IDS and takes all the relevant fields and exports it to a jetto.jset.

- Not necessarily in duqtools
- Some sort of config

```
ids2jetto g2aho/jet/1234/100 --template jetto.jset -o run_123/jetto.jset
# -> new jetto.jset
```

**Comment by v1kko** [comment]
Before we develop this tool we should ask Fransicus if there is any current development of a ids2jetto tool

**Comment by fcasson** [comment]
Possibly this issue should be divided up.  Taking Aaron's list

 *  machine: from input IDS -> basic manipulation using a new ids2jset.  The jetto.jset to jetto.in we already have in jetto-pythontools, just need to add a lookup
  *  shot: from input IDS  -> okay, basic manipulation on a ids2jset.  The jetto.jset to jetto.in we already have in jetto-pythontools, just need to add a lookup
  *  time_start: [float] or from input IDS -> If this is really universal that you want to start a sim from IDS times, this is also basic manipulation of jset and a new lookup in jetto-pythontools
  *  time_end: [float] or from input IDS -> As above
  *  major_radius: [float] or (from input IDS - not sure if possible) -> This should probably be done internally in jetto to actually read the IDS data.  Same for any other physics parameters.
  *  impurities: from input IDS -> need to clarfiy exactly what you want here, but probably should be done internally in jetto

**Comment by stefsmeets** [comment]
Hi @fcasson, is there a ready made lookup table available somewhere?

**Comment by fcasson** [comment]
Due to the way jams is built, lookups are not universal by attached to a specific template / use case.

There is short one in the jetto-pythontools docs, but here's an example I am working with at present (github does not support json upload??)

```
{
	"e_bohm_coeff": {
		"jset_id": "TransportStdAdvDialog.elecBohmCoeff",
		"nml_id": {
			"namelist": "NLIST3",
			"field": "XEBOHM"
		},
		"type": "real",
		"dimension": "scalar"
	},
	"i_bohm_coeff": {
		"jset_id": "TransportStdAdvDialog.ionBohmCoeff",
		"nml_id": {
			"namelist": "NLIST3",
			"field": "XIBOHM"
		},
		"type": "real",
		"dimension": "scalar"
	},
	"e_gbohm_coeff": {
		"jset_id": "TransportStdAdvDialog.elecGBohmCoeff",
		"nml_id": {
			"namelist": "NLIST3",
			"field": "XEGBOHM"
		},
		"type": "real",
		"dimension": "scalar"
	},
	"i_gbohm_coeff": {
		"jset_id": "TransportStdAdvDialog.ionGBohmCoeff",
		"nml_id": {
			"namelist": "NLIST3",
			"field": "XIGBOHM"
		},
		"type": "real",
		"dimension": "scalar"
	},
	"EC_power": {
		"jset_id": "ECRHPanel.norm.value[0]",
		"nml_id": {
			"namelist": "NLIST1",
			"field": "PTOTEC"
		},
		"type": "real",
		"dimension": "scalar"
	},
        "sptot": {
		"jset_id": null,
		"nml_id": {
			"namelist": "NLIST1",
			"field": "SPTOT"
		},
		"type": "real",
		"dimension": "scalar"
	},
	"Greenw_frac": {
		"jset_id": null,
		"nml_id": {
			"namelist": "NLIST1",
			"field": "DNEPFB"
		},
		"type": "real",
		"dimension": "vector"
	},
        "ECCD_eff": {
		"jset_id": null,
		"nml_id": {
			"namelist": "NLIST1",
			"field": "ECCDNORM"
		},
		"type": "int",
		"dimension": "scalar"
	},
	"PED_scal": {
		"jset_id": null,
		"nml_id": {
			"namelist": "NLIST1",
			"field": "CEPED1TPEDSCAL"
		},
		"type": "real",
		"dimension": "scalar"
	},
	"PED_mod": {
		"jset_id": null,
		"nml_id": {
			"namelist": "NLIST1",
			"field": "ITEREPED1PRED"
		},
		"type": "int",
		"dimension": "scalar"
	},
	"RR_scal": {
		"jset_id": "TransportStdAdvDialog.elecCDBMCoeff",
		"nml_id": {
			"namelist": "NLIST3",
			"field": "XECDBM"
		},
		"type": "real",
		"dimension": "scalar"
	},
	"RAD_frac": {
		"jset_id": "RadiationPanel.norm.value[0]",
		"nml_id": {
			"namelist": "NLIST1",
			"field": "PRAD"
		},
		"type": "real",
		"dimension": "scalar"
	}
}
```

**Comment by stefsmeets** [comment]
Thanks, this looks quite close to what we had in mind. I'd be happy to use whatever is available in jetto python tools if it does that.

**Comment by v1kko** [comment]
This is now partially supported in duqtools. I have created new issues for the things that still need to be done
- Issue #285 is about the time intervals
- Issue #286 for the impurities
