### ISSUE TITLE
Put config / data models in submodule

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#114]
I ran into a couple of issues in #105 managing circular imports with pydantic models. This seems to be a relatively common issue with defining types, i.e. models depending on one another.

For type checking, this is easily solved by putting imports in a `typing.TYPE_CHECKING` block / using `from __future__ import annotations`. With pydantic we may need to resort to using `BaseModel.update_forward_refs()` to achieve something similar: https://stackoverflow.com/questions/63420889/fastapi-pydantic-circular-references-in-separate-files/63425646#63425646

**Comment by v1kko** [comment]
Currently we do not have circular imports in pydantic, only with mypy (which is fixed with the `typing.TYPE_CHECKING`)

**Comment by stefsmeets** [comment]
This can be closed then?

**Comment by v1kko** [comment]
I guess
