### ISSUE TITLE
Submit command as a string instead of list

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#148]
@v1kko We specify the `submit.submit_command` as a list. Would it be easier to specify it as a string and split it later?

**Comment by v1kko** [comment]
Yeah that might be better, I don't expect any spaces in arguments within this command, and even then those could probably be escaped with `\` or quoted `" "`

**Comment by v1kko** [comment]
if `shell=True` in `subprocess.run` then a string can be passed instead of a list and conversion is not necessary

**Comment by v1kko** [comment]
I don't think that would be a problem for this application 
- The security is compromised by design because you can just specify `['bash','-c','cat','/etc/passwd']`  as the submit command in the config file and we do no checking on this
- It's not on a performance critical path
