### ISSUE TITLE
Confirmation Prompts

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#172]
For each command (except init, plot, dash) ask confirmation to the user

- [x] for each command list operations to be done
  - [x] create
  - [x] submit
  - [ ] cleanup (also list operations _not_ done)
- [x] confirmation for each command [Y/N]
  - [x] create
  - [x] submit
  - [x] cleanup

**Comment by stefsmeets** [comment]
> Perhaps this can be combined with an Operations Queue (operations are put in a queue, and only executed after confirmation)

Yeah, I was also thinking this could be useful. This way will also make it easier to implement a 'dry-run'. Essentially answering 'no' == '--dry-run'.

**Comment by v1kko** [comment]
Yes, I like that idea a lot
