### ISSUE TITLE
Improve textual output of duqtools

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#194]
Currently, its a proper mess, lets improve it:

- [x]  by default, put the logging stuff in a logging file
  - [x] create a flag to change this location
  - [x] create a flag to redirect this to stderr
- [x] make the operations queue application prompt more fancy
- [x] Implement a tqdm progress bar or the operations queue

**Comment by stefsmeets** [comment]
Do you want to use `click` for this as well?
https://click.palletsprojects.com/en/8.0.x/utils/
