### ISSUE TITLE
Interpolating 2D data fields as well

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#216]
- The only actual 2d field is `equilibrium/time_slice/*/profiles_2d/psi`
- There are more fields but they are not typically used and are in `/grid` and specified as two 1D arrays

**Comment by stefsmeets** [comment]
There is a scipy function for this:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html

**Comment by stefsmeets** [comment]
Should we use xarray here? https://docs.xarray.dev/

**Comment by stefsmeets** [comment]
I have now spent some time looking into this, and it really is a significant departure from what we have implemented so far. We had assumed 1d profiles from the beginning, in which case the pandas implementation we have now is fine.

So far we have used the `IDSMapping` to interface with the IMAS data. I'm trying to gather a bit what the requirements are for interfacing with these data.

- Must support grabbing a single path:
    - `core_profiles` -> `profiles_1d/0/t_i_average`
    - `core_profiles` -> `time`
    - `pulse_schedule` -> `flux_control/i_plasma/reference/data`
- Must support some sort of wild card for (time) slices:
    - `core_profiles` -> `profiles_1d/*/t_i_average`
    - `core_profiles` -> `profiles_1d/*/ion.element/*/a` (nested iter)
- Must support 0d, 1d, and 2d arrays.
- Must be able to write data back to the database entry.
- Must return a format that is convenient to work with, `pandas.DataFrame`, `xarray.Dataset` or equivalent
    - How are these data structured?
    - The data dictionary lists the coordinates for each variable, are these available from the database entry somehow?
- What do we with partial paths, i.e. the end is not a numpy array?
    - `ion.element/*`?
- Our code must be robust whatever happens to the backend. Whenever we get the HDF5 interface, will our code work without change?

**Comment by stefsmeets** [comment]
In #242 I added a `Variable` class, which we could use for storing Variable locations

- [ ] Get rid of prefix/vars which we use everywhere
- [ ] Re-implement rebasing `using xarray.Dataset`
- [ ] Define variables in config
    - I'm thinking to add a `variables` section to the `duqtools.yaml`, there you can define the variables, define their location and relationships, and then refer to them in the rest of the config by the given name. For example, in `create` or `merge`

```python
coord_vars = [Variable(
    name= 'time',
    ids= 'core_profiles',
    path= 'time',
    dims= ['time'],
    ),
]
data_vars = [
     Variable(
         name= 'xvar',
         ids= 'core_profiles',
         path= 'nested_profiles_1d/$time/data/grid',
         dims= ['x'],
     ),
     Variable(
         name= 'yvar',
         ids= 'core_profiles',
         path= 'nested_profiles_1d/$time/data/variable',
         dims= ['x'],
     )
]
```

**Comment by stefsmeets** [comment]
I think the notebook demonstrates how this can be approached (https://duqtools.readthedocs.io/en/latest/examples/xarray-2D/). I think this issue can be closed.
