### ISSUE TITLE
Create a --quiet mode (or a --loud mode)

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#221]

**Comment by v1kko** [comment]
I've decided to go for a `--quiet` option because I have yet to encounter a tool with a `--loud` flag.

Should we also silence the logging? I am not sure about that `--log /dev/null` would also do the trick if people want that

**Comment by stefsmeets** [comment]
`--loud` would be the equivalent of increased verbosity (`-v`) as some tools implement it. My preference would be to keep the standard out as minimal as possible and only add verbosity when asked for.

I'm just a bit worried about the end goal of all this increased complexity, and how the different streams are separated. The log file is already getting quite unwieldy.

It's difficult to control exactly what gets printed to stdout, with all the decorators that not only delay execution, but also that these messages are essentially hidden from the code.

**Comment by v1kko** [comment]
I agree, this is all non-essential features that do bloat the code.
Suggestion: I can create a separate logger for things that have to be printed to the screen (its already done that way in the Operations) but then other parts of the code also have easy access to it. then to manipulate screen/log output we just have to change those loggers.
