### ISSUE TITLE
Fix the llcmd file to reflect correct user choices

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#227]
- [x] time limit
- [x] number of processors
- [x] gw
- [x] Update job name to include 'duqtools'

Or just copy it from the template directory

**Comment by stefsmeets** [comment]
I think 'just copying' from the template directory is going to involve writing some sort of parser. 

Easier, I think, to make these configurable fields in the submit section of the config.

**Comment by v1kko** [comment]
What about making it part of the `System` ? such that we can query it for the jetto Sytem now, but can implement it as part of the configuration  for a future `System` implementation

**Comment by stefsmeets** [comment]
Yeah, putting it under `System` works. 👍

After I commented I thought it didn't feel right to put it under `submit`. It didn't feel right to put it in `create` either.
