### ISSUE TITLE
Clean `duqtools create` output

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#232]
The duqtools create output is a bit verbose and difficult to read, this could be cleaned up to just print the imas data or run directories that will be created. I.e. make it more in line with `duqtools clean` or `duqtools submit`, which look much friendlier.

Also the progress bar is a bit finicky on my side (flickers a lot).

**Comment by stefsmeets** [comment]
Hi @v1kko , I spent some time looking at this today, but I cannot come up with any good ways of doing this. Do you have any suggestions?

**Comment by v1kko** [comment]
I have a brewing idea, but I would have to try to know for sure it would work:

add a `display` keyword argument to the `Operation` class, then in the `apply_all` just only display the ones with `display` set to `True`. I wouldn't know which default would be best, perhaps `True`, then we should add `False` to all inner operations
