### ISSUE TITLE
Mock IMAS data class and attributes for tests

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#27]
As a software developer, I want to have access to a class with the IMAS structure, so that I can develop my code locally and test it in an isolated environment (i.e. CI).

We can't install the infrastructure to run IMAS/IMASPy locally for now. So this should be some sort of data class or dictionary with dummy attributes mimicking IMAS.

**Comment by stefsmeets** [comment]
On the same note, IMAS is not available on `pypi`, so it is difficult to install it on a VM to test using Github actions. For now I have made the IMAS install optional in `setup.cfg` in #35 until we find a better solution.

**Comment by stefsmeets** [comment]
See also #151

**Comment by stefsmeets** [comment]
I changed the tests in #187 to skip some tests when imas can not be imported. In this way, we can the tests in some capacity on github actions / windows.

**Comment by v1kko** [comment]
I accidentally implemented this, as I wanted to run those tests locally, and I also re-enabled the tests in pull request #269
