### ISSUE TITLE
Read in IMAS data

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#3]
There are 2 options for reading IMAS data:
- IMAS Python HLI (legacy)
- IMASPy, newer, pure Python interface which is a bit higher level

There are 2 backends:
- MDS+ (proprietary, slow, large files)
- HDF5 (newer, faster, smaller files, available soon)

Prefer IMASPy + HDF5 where possible.

**Comment by stefsmeets** [comment]
I think we now got some grip on loading data. I made a new issue to support HDF5 when available: #76
