### ISSUE TITLE
Implement plot with reference time slice

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#308]
We should have a function or method that plots some IMAS data. 

- Uses altair for interactive time slices
- It should have the option to plot a reference line. The slider will show a different time slice. See plot example below.

**Comment by aaronkho** [comment]
Attached as example
![image](https://user-images.githubusercontent.com/23500973/192522602-8e828a01-c1e0-4cfd-bdf8-0c43816109da.png)
