### ISSUE TITLE
Update plot CLI interface

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#309]
See example from Aaron below.

We should then define a globalish variable definition config, i.e. what is now under variables in `duqtools.yaml`. This can be defined in some user config file (`~/.duqtools`) or via some location defined by an environment variable.

**Comment by aaronkho** [comment]
As example:
`python compare_im_runs.py -d jet -s 97781 -r 5 700 --time_begin 49.25 --time_end 50.25 --steady_state -sig core_profiles.profiles_1d[].electrons.temperature`

**Comment by stefsmeets** [comment]
Depends on #313
