### ISSUE TITLE
UQ for imas data and/or UQ for Jetto configuration files

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#31]
@jcitrin We have a question about the scope of the UQ and it would be great to have your opinion this topic:

we want to start with UQ for the 'data', but it is also possible to do some UQ with the variables in jetto.{s}in, would this be something that is desired in the future ? Or is a single Jetto configuration enough (for now).

Related, does changing the data change settings in the jetto input files? If so we have to take that into account ...

Cheers,
Victor

**Comment by jcitrin** [comment]
> but it is also possible to do some UQ with the variables in jetto.{s}in
Yes, it could also be interesting in principle. But that will most likely be UQ of code-specific parameters (various physics and numerics flags, etc), which is a very different type of UQ to compared to the propagation of experimental uncertainties in specific prescribed data which is what we're now focusing on. We should discuss together with Aaron at some point

> Related, does changing the data change settings in the jetto input files? If so we have to take that into account ...
The only thing that should change at this point in the jetto input files is the location of the IDS that is imported into the simulation.

**Comment by stefsmeets** [comment]
I wrote some basic io for the `jetto.in` / `jetto.jset` configs this week (#29, #32), so we can work this into the UQ workflow at some point (depending on what is needed).

The python config file: (`jintrac_imas_config.cfg`) gets written by the python script `workflow_readwrite.py` at some point after the run is started. We will need to figure out where it gets its input from and how to manipulate it.

Sample `workflow_readwrite.py`:
```
!****************************************************************
! Workflow configuration file - copy this to the run directory
!
! File generated by python script workflow_readwrite.py
!
! Workflow: Generic JINTRAC workflow
!
94875                ! Input IDS shot
2                    ! Input IDS run
jet                  ! Input IDS machine
g2aho                ! Input IDS user (username at JET, public at ITER, or directory full path name)
94875                ! Output IDS shot
251                  ! Output IDS run
jet                  ! Output IDS machine
g2ssmee              ! Output IDS user
48.35                ! Start time
49.0                 ! End time
1                    ! Replace existing IDS (0-no, else yes)
2                    ! Number of processors for parallelised actors
JETTO,IDSOUT,IDSIN   ! Active components e.g. EDGE2D,JETTO,HCD (uppercase)
```

All these parameters are in the `jetto.jset` files (some of them multiple times).

**Comment by stefsmeets** [comment]
Found the file in the jintrac repo: `https://git.iter.org/projects/SCEN/repos/jintrac/browse/python/workflow_readwrite.py`

**Comment by jcitrin** [comment]
None of the input IDS and output IDS info which are in the jset and cfg files, are in `jetto.in` . So `jetto.in` does not need to be changed to be consistent.

From what I gathered from looking at the code, the only file which needs to be modified is `jetto.jset`. Then, upon launch, there are internal scripts (see in the JINTRAC repository `sh/createworkflowcfg` which invokes `python/workflow_readwrite.py` ) that sets up the Python cfg file based on what is inside the `jetto.jset`

**Comment by stefsmeets** [comment]
In the config we could do something like:

```yaml
create:
  template:
    user: user
    db: jet
    shot: 92432
    run: 1
  # intermediate files with modified ids data are stored here
  intermediate:
    db: jet
    shot: 92432
    runs_start_at: 1000
  # these ids paths store the output of the simulation runs
  output:
    db: jet
    shot: 92432
    runs_start_at: 2000
```

The run number for intermedate / output are starting points. Because we need to store a large number of data, we should reserve a sequence of runs for these. Perhaps it makes sence to store intermediate data in a separate db?

**Comment by stefsmeets** [comment]
This is clear now, I'm closing this issue.
