### ISSUE TITLE
Dont error on extra fields in the config file, but print a warning

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#315]

**Comment by stefsmeets** [comment]
Why is this necessary? I assume that extra fields are always typo's, and warnings may get lost in the noise of the stdout. In that case the code will still run, but with default values (if present).

**Comment by stefsmeets** [comment]
Seems like a non-issue to me. If this is a problem then we should fix the interface for the sampler than to globally allow extra fields.
