### ISSUE TITLE
variable.yaml enhancements

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#326]
This PR tracks a list of improvements to the `variables.yaml` file.

- [x] Add option to specify location of `variables.yaml` in `duqtools.yaml`, i.e. `variables_file: Optional[Path]` -> Do this later if necessary, there is enough flexiblity at the moment.
- [x] Add option to specify extra variables in `duqtools.yaml`, because it is somewhat cumbersome to have to copy the `variables.yaml`, modify it and then use it. -> #346
- [x] Get list of sensible defaults from @aaronkho 
- [x] Expose list of default variable names on the documentation
- [x] `duqtools list` -> New cli command to list variables -> #346

Covered these in #339:
- [ ] Copy `variable.yaml` to duqtools workspace
- [ ] Log location of `variables.yaml` used -> this is already in `runs.yaml`

_Originally posted by @v1kko in https://github.com/CarbonCollective/fusion-dUQtools/issues/320#issuecomment-1263226840_:

        Looks good, this should reduce config file bloat a lot

- I like the modularity, we can always add an option to load the default config file in another way later:
 `variables_file: Optional[Path]` as an extra option for example

I have one question/suggestion:
- What happens if I want to only add 1 extra variable? It looks like I'd have to copy the default, add my stuff, and store it somewhere where `duqtools` will pick it up, and in that way the defaults would be replaced forever, even if they are updated in a later version.
  - Maybe it is good to still have  way to define 'extra' variables, which do not replace the default files, this could be done with an extra `extra_variables: Optional[Path]` in the config file, which is then appended/overwritten to the defaults

**Comment by aaronkho** [comment]
Here is a list of variables that would probably be useful to look expose to the user at all times, as they are very useful to any type of validation. The commented variables cause `duqtools` to error out, typically from a `KeyError` though. Has the fix discussed last week (provide a null value for missing fields) been implemented?
[variables.txt](https://github.com/CarbonCollective/fusion-dUQtools/files/9708832/variables.txt)

**Comment by stefsmeets** [comment]
Hi @aaronkho , thanks for the really nice list! I think this will make a big step in the usability of the code. I will add it in #346.

The fix for actual missing fields is something we still need to think about how to implement. I will create a new issue to make sure we don't forget.
