### ISSUE TITLE
duqtools (re-)create single point from runs.yaml

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#339]
Sometimes one wants to edit a single point, duqtools should be able to do this.

Somthing like
```
duqtools create --recreate run_0002
```

**Comment by stefsmeets** [comment]
`duqtools create --re run_0002` -> read `runs.yaml` and re-create this run directory.

**Comment by stefsmeets** [comment]
Decided to go with `duqtools recreate run_0000 run_0001` and implement it as a new subcommand not to overload the existing `create` function.
