### ISSUE TITLE
Implement dry run option

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#72]
For testing it may be useful to have some sort of `--dry-run` option, which logs the steps, but does not create/move data, or execute simulations.

**Comment by v1kko** [comment]
Good Idea, I think if we want to implement this we should contain all operations that have side-effects on the filesystem in separate classes (already the case for IDS). such that we can implement the switch there.

**Comment by stefsmeets** [comment]
This may need some refactoring of the code to avoid having `if dry-run: ...` littered throughout the functions, especially the create step.

**Comment by v1kko** [comment]
I think I can start here with using the new "System" based system, and using the Dummy system.

- [ ] For any remaining side-effects, decide if they are worth porting to the System infrastructure, of use an if-statement in-place
