### ISSUE TITLE
duqtools - cleanup command

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#96]
Remove any IDS generated by duqtools and clean run directories.

**Comment by stefsmeets** [comment]
This should read `runs.yaml` to figure out which ids have been written for this directory. It also contains a list of the run directories, but it may make more sense to delete all subdirectories.

- [ ] Delete ids data (check runs.yaml)
- [ ] Delete runs.yaml (check `Runs` in `create.py` for `BaseModel`)
- [ ] Delete subdirectories defined in `runs.yaml`
- [ ] Delete other subdirectories matching our structure (i.e. `cfg.workspace.cwd.glob('run_*')`)
